FORMAT: 1A

# Group Station
## Create Station [/api/stations]
###  Create Station [POST]

Criação de uma estação

+ name - nome da estação
+ lineReference - linha a qual a estação pertence
+ accessibilityItems - array com os itens de acessibilidade da estação

+ Request (application/json)

        {
            "name": "liberdade",
            "lineReference": "azul",
            "accessibilityItems": [
                "elevador",
                "rampa",
                "linha no chão"
                ]
        }


+ Response 201 (application/json)

        {
            "name": "jabaquara",
            "accessibilityItems": [
                "elevador",
                "rampa",
                "linha no chão"
            ],
            "lineReference": "amarela",
            "_id": "625ad3a49b52918673211339",
            "createdAt": "2022-04-16T14:33:08.551Z",
            "updatedAt": "2022-04-16T14:33:08.551Z"
        }

## Get stations [/api/stations?name={name}&reference={reference}]
### Get Wallet [GET]


+ Parameters
    + name (string, optional) - nome da estação
    + reference (string, optional) - nome da linha a qual a estação pertence


+ Response 200 (application/json)

        [
            {
                "_id": "625ad340823df63f6ecca555",
                "name": "veracruz",
                "accessibilityItems": [
                    "elevador",
                    "rampa",
                    "linha no chão"
                ],
                "lineReference": "amarela",
                "createdAt": "2022-04-16T14:31:28.869Z",
                "updatedAt": "2022-04-16T14:31:28.869Z"
            }
        ]

